// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectAccessManagement.Repository;

#nullable disable

namespace ProjectAccessManagement.Repository.Migrations
{
    [DbContext(typeof(ProjectAccessManagementContext))]
    [Migration("20250326220400_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectAccessManagement.Domain.Entities.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AppType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("ProjectAccessManagement.Domain.Entities.Automation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessAreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessAreaId");

                    b.ToTable("Automations");
                });

            modelBuilder.Entity("ProjectAccessManagement.Domain.Entities.BusinessArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusinessAreas");
                });

            modelBuilder.Entity("ProjectAccessManagement.Domain.Entities.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowsMultiAccess")
                        .HasColumnType("bit");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AutomationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CredentialType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("AutomationId");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("ProjectAccessManagement.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AutomationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CredentialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("AutomationId");

                    b.HasIndex("CredentialId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("ProjectAccessManagement.Domain.Entities.Automation", b =>
                {
                    b.HasOne("ProjectAccessManagement.Domain.Entities.BusinessArea", "BusinessArea")
                        .WithMany("Automations")
                        .HasForeignKey("BusinessAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessArea");
                });

            modelBuilder.Entity("ProjectAccessManagement.Domain.Entities.Credential", b =>
                {
                    b.HasOne("ProjectAccessManagement.Domain.Entities.App", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectAccessManagement.Domain.Entities.Automation", null)
                        .WithMany("Credentials")
                        .HasForeignKey("AutomationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("ProjectAccessManagement.Domain.Entities.Module", b =>
                {
                    b.HasOne("ProjectAccessManagement.Domain.Entities.App", "Application")
                        .WithMany("Modules")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectAccessManagement.Domain.Entities.Automation", null)
                        .WithMany("Modules")
                        .HasForeignKey("AutomationId");

                    b.HasOne("ProjectAccessManagement.Domain.Entities.Credential", null)
                        .WithMany("Modules")
                        .HasForeignKey("CredentialId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("ProjectAccessManagement.Domain.Entities.App", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("ProjectAccessManagement.Domain.Entities.Automation", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("ProjectAccessManagement.Domain.Entities.BusinessArea", b =>
                {
                    b.Navigation("Automations");
                });

            modelBuilder.Entity("ProjectAccessManagement.Domain.Entities.Credential", b =>
                {
                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
