name: CI/CD - ProjectAccessManagement

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_IMAGE_NAME: projectaccessmanagementapi

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restaurar dependências
      run: dotnet restore ProjectAccessManagement.sln

    - name: Compilar a solução
      run: dotnet build ProjectAccessManagement.sln --configuration Release --no-restore

    - name: Executar testes
      run: dotnet test ProjectAccessManagement.sln --verbosity normal

    - name: Login no Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build da imagem Docker
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest \
        -f ProjectAccessManagement.API/Dockerfile .

    - name: Push da imagem para o Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
